// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"LK/pkg/models/shared"
	"net/http"
)

type LoginAPIV1TokenPostResponse struct {
	ContentType string
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
	StatusCode          int
	RawResponse         *http.Response
	// Successful Response
	LoginAPIV1TokenPost200ApplicationJSONAny interface{}
}
