// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"LK/pkg/models/shared"
	"net/http"
)

type OrderSchemaAPIV1OrdersSchemaGetResponse struct {
	ContentType string
	// Successful Response
	Response    *shared.Response
	StatusCode  int
	RawResponse *http.Response
}
