// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"LK/pkg/models/shared"
	"net/http"
)

type OrderValidatedAPIV1OrdersPostSecurity struct {
	OAuth2PasswordBearer string `security:"scheme,type=oauth2,name=Authorization"`
}

type OrderValidatedAPIV1OrdersPostResponse struct {
	ContentType string
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
	// Successful Response
	Response    *shared.Response
	StatusCode  int
	RawResponse *http.Response
}
