// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"LK/pkg/models/shared"
	"net/http"
)

type StatusValidatedAPIV1OrdersOrderIDStatusPostSecurity struct {
	OAuth2PasswordBearer string `security:"scheme,type=oauth2,name=Authorization"`
}

type StatusValidatedAPIV1OrdersOrderIDStatusPostRequest struct {
	OrderStatus shared.OrderStatus `request:"mediaType=application/json"`
	OrderID     int64              `pathParam:"style=simple,explode=false,name=order_id"`
}

type StatusValidatedAPIV1OrdersOrderIDStatusPostResponse struct {
	ContentType string
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
	// Successful Response
	Response    *shared.Response
	StatusCode  int
	RawResponse *http.Response
}
