// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"LK/pkg/models/shared"
	"net/http"
)

type TicketStatusAPIV1TicketTicketIDCommentPostSecurity struct {
	OAuth2PasswordBearer string `security:"scheme,type=oauth2,name=Authorization"`
}

type TicketStatusAPIV1TicketTicketIDCommentPostRequest struct {
	OrderTicket shared.OrderTicket `request:"mediaType=application/json"`
	TicketID    string             `pathParam:"style=simple,explode=false,name=ticket_id"`
}

type TicketStatusAPIV1TicketTicketIDCommentPostResponse struct {
	ContentType string
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
	// Successful Response
	Response    *shared.Response
	StatusCode  int
	RawResponse *http.Response
}
