// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BodyLoginAPIV1TokenPost struct {
	ClientID     *string `form:"name=client_id"`
	ClientSecret *string `form:"name=client_secret"`
	GrantType    *string `form:"name=grant_type"`
	Password     string  `form:"name=password"`
	Scope        *string `form:"name=scope"`
	Username     string  `form:"name=username"`
}
