// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// HTTPValidationError - Validation Error
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}
