// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Item - Represents info about each position in order
type Item struct {
	// Item name
	Name string `json:"name"`
	// This field could be decimal string
	Price float64 `json:"price"`
	// This field could be numeric string
	Quantity int64 `json:"quantity"`
	// This field could be numeric string
	Sku int64 `json:"sku"`
}
