// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NPPackStation - Represents info about shipping via `Nova Posta PackStation` method
type NPPackStation struct {
	City                  string `json:"city"`
	CityID                string `json:"city_id"`
	Comment               string `json:"comment"`
	Region                string `json:"region"`
	RegionID              string `json:"region_id"`
	SettlementDescription string `json:"settlement_description"`
	SettlementType        string `json:"settlement_type"`
	// Represents info about street
	Street      Street `json:"street"`
	WarehouseID string `json:"warehouse_id"`
	// This field could be numeric string
	WarehouseNumber int64 `json:"warehouse_number"`
}
