// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Order - Represents full info about order
type Order struct {
	// Format YYYY-MM-DD[T]HH:MM
	CreatedAt time.Time `json:"created_at"`
	// Represents info about order customer
	Customer Customer `json:"customer"`
	Items    []Item   `json:"items"`
	// This field could be numeric string
	MerchantID int64 `json:"merchant_id"`
	// This field could be numeric string
	OrderID int64 `json:"order_id"`
	// Represents info about order payment
	Payment Payment `json:"payment"`
	// Represents info about shipping order
	Shipping Shipping `json:"shipping"`
}
