// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OrderStatuses int64

const (
	OrderStatusesZero OrderStatuses = 0
	OrderStatusesOne  OrderStatuses = 1
)

func (e OrderStatuses) ToPointer() *OrderStatuses {
	return &e
}

func (e *OrderStatuses) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		*e = OrderStatuses(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderStatuses: %v", v)
	}
}
