// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OrderStatus - Represents info about new order status
type OrderStatus struct {
	// This field could be numeric string
	OrderID int64 `json:"order_id"`
	// This field could be numeric string
	Status OrderStatuses `json:"status"`
}
