// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Payment - Represents info about order payment
type Payment struct {
	// This field could be numeric string
	Method PaymentMethod `json:"method"`
	// This field could be numeric string
	Status PaymentStatus `json:"status"`
}
