// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PaymentMethod - An enumeration.
type PaymentMethod int64

const (
	PaymentMethodZero PaymentMethod = 0
	PaymentMethodOne  PaymentMethod = 1
)

func (e PaymentMethod) ToPointer() *PaymentMethod {
	return &e
}

func (e *PaymentMethod) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		*e = PaymentMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethod: %v", v)
	}
}
