// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PaymentStatus - An enumeration.
type PaymentStatus int64

const (
	PaymentStatusZero PaymentStatus = 0
)

func (e PaymentStatus) ToPointer() *PaymentStatus {
	return &e
}

func (e *PaymentStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		*e = PaymentStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentStatus: %v", v)
	}
}
