// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Recipient - Represents info about recipient
type Recipient struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
	Phone      string `json:"phone"`
}
