// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Response - Successful Response
type Response struct {
	Data    map[string]interface{} `json:"data,omitempty"`
	Errors  []string               `json:"errors,omitempty"`
	Success bool                   `json:"success"`
}
