// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ResponseData struct {
}

// Response - Successful Response
type Response struct {
	Data    *ResponseData `json:"data,omitempty"`
	Errors  []string      `json:"errors,omitempty"`
	Success bool          `json:"success"`
}
