// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ShippingMethod string

const (
	ShippingMethodNovaposhtaPackstation ShippingMethod = "novaposhta_packstation"
)

func (e ShippingMethod) ToPointer() *ShippingMethod {
	return &e
}

func (e *ShippingMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "novaposhta_packstation":
		*e = ShippingMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShippingMethod: %v", v)
	}
}

// Shipping - Represents info about shipping order
type Shipping struct {
	// Represents info about shipping via `Nova Posta PackStation` method
	Address NPPackStation  `json:"address"`
	Method  ShippingMethod `json:"method"`
	Price   *float64       `json:"price,omitempty"`
	// Represents info about recipient
	Recipient Recipient `json:"recipient"`
}
