// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ValidationError struct {
	Loc  []interface{} `json:"loc"`
	Msg  string        `json:"msg"`
	Type string        `json:"type"`
}
